[project]
Backend = openxc7
Part = xc7k160tffg676-2
Top = enclustra_ddr3
Constraint = enclustra_ddr3.xdc
Sources = ./ddr3_top.v,./ddr3_controller.v,./ddr3_phy.v,./enclustra_ddr3.v,./uart_rx.v,./uart_tx.v,./clk_wiz.v 

[caas]
Server = https://caas.symbioticeda.com:18888/


